//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetierSharedMemory.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Td_Erreur
    {
        [Key]
        public int id { get; set; }
        public Nullable<System.DateTime> DateErreur { get; set; }
        public string DescriptionErreur { get; set; }
        public string TitreErreur { get; set; }
    }
}
